-- Carga inicial del catálogo REAL, generada desde el Excel del repo
-- POWERMX-sitio (Inventario/inventario_productos.xlsx, 42 KB).
-- Correr DESPUÉS de 01_productos.sql. Reemplaza al 02 anterior.

insert into productos (sku, categoria, nombre, marca, modelo, descripcion, precio, precios, unidad, atributos) values
  ('GEN-IQ2KW', 'generador', 'GP2200I INVERTER', 'GENERAC', 'GP2200I INVERTER', 'Generador inverter portátil, silencioso. Ideal para casa, camping y pequeñas cargas.', 18500, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gasolina", "kw": 2.2, "arranque": "Manual", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": "100 HORAS DE OPERACIÓN O 1 AÑO", "ats": "no"}'::jsonb),
  ('GEN-IQ3KW', 'generador', 'IQ3500 INVERTER', 'GENERAC', 'IQ3500 INVERTER', 'Inverter de alta eficiencia con modo Eco. Operación ultra silenciosa.', 24900, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gasolina", "kw": 3, "arranque": "Eléctrico", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": "100 HORAS DE OPERACIÓN O 1 AÑO", "ats": "no"}'::jsonb),
  ('GAS-GP3600', 'generador', 'GP3600', 'GENERAC', 'GP3600', 'Generador abierto para respaldo de pequeñas cargas.', 21500, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gasolina", "kw": 3.6, "arranque": "Manual", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": "100 HORAS DE OPERACIÓN O 1 AÑO", "ats": "no"}'::jsonb),
  ('GAS-GP8000E', 'generador', 'GP8000E', 'GENERAC', 'GP8000E', 'Opción económica para respaldo básico del hogar. Compacto y fácil de transportar.', 14900, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gasolina", "kw": 8, "arranque": "Eléctrico", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": "100 HORAS DE OPERACIÓN O 1 AÑO", "ats": "no"}'::jsonb),
  ('GAS-CX8000', 'generador', 'CX8000', 'POWERMATE', 'CX8000', 'Generador inverter con tecnología QuietPower. Panel de control intuitivo.', 28500, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gasolina", "kw": 8, "arranque": "Eléctrico", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": "100 HORAS DE OPERACIÓN O 1 AÑO", "ats": "no"}'::jsonb),
  ('GAS-CX5500', 'generador', 'CX5500', 'POWERMATE', 'CX5500', 'Generador standby con ATS incluido. Arranca solo ante un corte de luz. Gas natural o LP.', 38000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gasolina", "kw": 5.5, "arranque": "Manual", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": "101 HORAS DE OPERACIÓN O 1 AÑO", "ats": "no"}'::jsonb),
  ('GAS-PM3800', 'generador', 'PM3800', 'POWERMATE', 'PM3800', 'Planta de respaldo comercial. Arranque automático en menos de 10 segundos.', 52000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gasolina", "kw": 3.8, "arranque": "Manual", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": "102 HORAS DE OPERACIÓN O 1 AÑO", "ats": "no"}'::jsonb),
  ('AIR-10KW', 'generador', 'AIRCOOLED 10KW', 'GENERAC', 'AIRCOOLED 10KW', 'Planta standby gas LP/natural. Ideal para clínicas, escuelas y edificios de oficinas.', 34500, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 10, "arranque": "Automático", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": 3, "ats": "no"}'::jsonb),
  ('AIR-14KW', 'generador', 'AIRCOOLED 14KW', 'GENERAC', 'AIRCOOLED 14KW', 'Planta standby gas LP/natural. Ideal para clínicas, escuelas y edificios de oficinas.', 68000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 14, "arranque": "Automático", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": 3, "ats": "si"}'::jsonb),
  ('AIR-18KW', 'generador', 'AIRCOOLED 18KW', 'GENERAC', 'AIRCOOLED 18KW', 'Planta standby gas LP/natural. Ideal para clínicas, escuelas y edificios de oficinas.', 48500, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 18, "arranque": "Automático", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": 3, "ats": "si"}'::jsonb),
  ('AIR-20KW', 'generador', 'AIRCOOLED 20KW', 'GENERAC', 'AIRCOOLED 20KW', 'Planta standby gas LP/natural. Ideal para clínicas, escuelas y edificios de oficinas.', 89000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 20, "arranque": "Automático", "fase": "Trifásico", "voltaje": "110/208V", "garantia_anios": 3, "ats": "si"}'::jsonb),
  ('AIR-22KW', 'generador', 'AIRCOOLED 22KW', 'GENERAC', 'AIRCOOLED 22KW', 'Planta standby gas LP/natural. Ideal para clínicas, escuelas y edificios de oficinas.', 95000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 22, "arranque": "Automático", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": 3, "ats": "si"}'::jsonb),
  ('AIR-24KW', 'generador', 'AIRCOOLED 24KW', 'GENERAC', 'AIRCOOLED 24KW', 'Planta standby gas LP/natural. Ideal para clínicas, escuelas y edificios de oficinas.', 112000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 24, "arranque": "Automático", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": 3, "ats": "si"}'::jsonb),
  ('AIR-26KW', 'generador', 'AIRCOOLED 26KW', 'GENERAC', 'AIRCOOLED 26KW', 'Planta standby gas LP/natural. Ideal para clínicas, escuelas y edificios de oficinas.', 74000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 26, "arranque": "Automático", "fase": "Monofásico", "voltaje": "120/240V", "garantia_anios": 3, "ats": "si"}'::jsonb),
  ('LIQ-32', 'generador', 'LIQUIDCOOLED 32KW', 'GENERAC', 'LIQUIDCOOLED 32KW', 'Planta industrial 55 kW para manufactura y hospitales. Tablero de transferencia incluido.', 185000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 32, "arranque": "Automático", "fase": "Trifásico", "voltaje": "208/480V", "garantia_anios": 3, "ats": "si"}'::jsonb),
  ('LIQ-34', 'generador', 'LIQUIDCOOLED 32KW', 'GENERAC', 'LIQUIDCOOLED 32KW', 'Planta industrial 55 kW para manufactura y hospitales. Tablero de transferencia incluido.', 185000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "combustible": "gas", "kw": 34, "arranque": "Automático", "fase": "Trifásico", "voltaje": "208/480V", "garantia_anios": 3, "ats": "si"}'::jsonb),
  ('BAT-PYLONTECH-US2000C', 'bateria', 'US2000C', 'PYLONTECH', 'US2000C', 'La batería residencial más vendida del mundo. Apilable hasta 8 unidades. Sin mantenimiento.', 22000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "kwh": 2.4, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "48V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-PYLONTECH-US3000C', 'bateria', 'US3000C', 'PYLONTECH', 'US3000C', 'Sistema compacto para hogares con consumo medio. Compatible con inversores GroWatt híbridos.', 31000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "kwh": 3.5, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "48V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-BYD-BATTERY-BOX-5KWH', 'bateria', 'Battery-Box 5kWh', 'BYD', 'Battery-Box 5kWh', 'LiFePO4 sin mantenimiento. Compatible con Fronius, SMA, Solis y GroWatt.', 48000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "kwh": 5, "quimica": "LiFePO4", "ciclos": "8000+", "voltaje": "48V", "dod": "100%", "garantia_anios": "10"}'::jsonb),
  ('BAT-GROWATT-ARK-2-56H', 'bateria', 'ARK 2.56H', 'GROWATT', 'ARK 2.56H', 'Integración directa con inversores GroWatt híbridos. Monitoreo vía app ShinePhone.', 24500, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "kwh": 2.56, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "48V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-SOLIS-RHI-BAT-6KWH', 'bateria', 'RHI Bat 6kWh', 'SOLIS', 'RHI Bat 6kWh', 'Sistema todo-en-uno con inversor híbrido incluido. Plug-and-play residencial.', 56000, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "kwh": 6, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "48V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-TROJAN-T-105-AGM', 'bateria', 'T-105 AGM', 'TROJAN', 'T-105 AGM', 'Batería AGM para sistemas básicos o respaldo. Sin mantenimiento, sin ventilación requerida.', 4800, '{}'::jsonb, 'pieza', '{"segmento": "residencial", "kwh": 1.35, "quimica": "AGM", "ciclos": "1200+", "voltaje": "6V", "dod": "50%", "garantia_anios": "2"}'::jsonb),
  ('BAT-PYLONTECH-FORCE-H2', 'bateria', 'Force H2', 'PYLONTECH', 'Force H2', 'Sistema apilable para comercios. Escala hasta 64 kWh en una sola cadena.', 98000, '{}'::jsonb, 'pieza', '{"segmento": "comercial", "kwh": 10.65, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "48V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-BYD-BATTERY-BOX-PREMIUM-15KWH', 'bateria', 'Battery-Box Premium 15kWh', 'BYD', 'Battery-Box Premium 15kWh', 'Alto voltaje para sistemas comerciales trifásicos. Gestión BMS integrado.', 148000, '{}'::jsonb, 'pieza', '{"segmento": "comercial", "kwh": 15.4, "quimica": "LiFePO4", "ciclos": "8000+", "voltaje": "48V", "dod": "100%", "garantia_anios": "10"}'::jsonb),
  ('BAT-GROWATT-ARK-HV-20KWH', 'bateria', 'ARK HV 20kWh', 'GROWATT', 'ARK HV 20kWh', 'Sistema de alto voltaje para comercio e industria ligera. Alta densidad de energía.', 185000, '{}'::jsonb, 'pieza', '{"segmento": "comercial", "kwh": 20, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "204V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-SOFAR-BTS-E20-DS5', 'bateria', 'BTS E20-DS5', 'SOFAR', 'BTS E20-DS5', 'Batería comercial modular. Gestión activa de celdas para máxima vida útil.', 190000, '{}'::jsonb, 'pieza', '{"segmento": "comercial", "kwh": 20, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "204V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-VISION-HF12-200A-AGM', 'bateria', 'HF12-200A AGM', 'VISION', 'HF12-200A AGM', 'AGM industrial para respaldo de sistemas de comunicación y UPS comerciales.', 9500, '{}'::jsonb, 'pieza', '{"segmento": "comercial", "kwh": 2.4, "quimica": "AGM", "ciclos": "1500+", "voltaje": "12V", "dod": "50%", "garantia_anios": "3"}'::jsonb),
  ('BAT-DYNESS-POWERRACK-B4850', 'bateria', 'PowerRack B4850', 'DYNESS', 'PowerRack B4850', 'Rack de baterías para escala comercial grande. BMS integrado de nivel industrial.', 420000, '{}'::jsonb, 'pieza', '{"segmento": "comercial", "kwh": 48.5, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "409V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-CATL-ENERC-100KWH', 'bateria', 'EnerC 100kWh', 'CATL', 'EnerC 100kWh', 'Sistema industrial 100 kWh. Para centros de datos, hospitales y manufactura crítica.', 980000, '{}'::jsonb, 'pieza', '{"segmento": "industrial", "kwh": 100, "quimica": "Li-ion", "ciclos": "8000+", "voltaje": "768V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-BYD-MC-CUBE-T', 'bateria', 'MC Cube-T', 'BYD', 'MC Cube-T', 'Contenedor BESS para almacenamiento a escala de red. Refrigeración líquida incluida.', 2100000, '{}'::jsonb, 'pieza', '{"segmento": "industrial", "kwh": 215, "quimica": "LiFePO4", "ciclos": "10000+", "voltaje": "1000V", "dod": "95%", "garantia_anios": "15"}'::jsonb),
  ('BAT-PYLONTECH-POWERCUBE-X-RC15', 'bateria', 'PowerCube X RC15', 'PYLONTECH', 'PowerCube X RC15', 'Sistema modular para parques solares y proyectos BESS. Expansión sin límite de capacidad.', 3600000, '{}'::jsonb, 'pieza', '{"segmento": "industrial", "kwh": 372, "quimica": "LiFePO4", "ciclos": "8000+", "voltaje": "1500V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-CATL-ENERONE-50KWH', 'bateria', 'EnerOne 50kWh', 'CATL', 'EnerOne 50kWh', 'Armario de baterías para industria mediana. Integración SCADA y gestión remota.', 520000, '{}'::jsonb, 'pieza', '{"segmento": "industrial", "kwh": 50, "quimica": "Li-ion", "ciclos": "8000+", "voltaje": "614V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-DYNESS-INDUSTRIAL-75KWH', 'bateria', 'Industrial 75kWh', 'DYNESS', 'Industrial 75kWh', 'Sistema llave en mano para instalaciones industriales. Certificaciones UL/IEC incluidas.', 740000, '{}'::jsonb, 'pieza', '{"segmento": "industrial", "kwh": 75, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "614V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('BAT-GROWATT-SPF-3000TL-HV', 'bateria', 'SPF 3000TL HV', 'GROWATT', 'SPF 3000TL HV', 'Sistema solar + batería integrado para industria ligera. Inversor trifásico GroWatt incluido.', 295000, '{}'::jsonb, 'pieza', '{"segmento": "industrial", "kwh": 30, "quimica": "LiFePO4", "ciclos": "6000+", "voltaje": "409V", "dod": "95%", "garantia_anios": "10"}'::jsonb),
  ('SOL-PAN-JINKO-450W', 'panel', 'Panel Solar Jinko 450W Monocristalino', 'Jinko', null, 'Panel solar monocristalino de alta eficiencia. Usado para armar los paquetes residenciales.', 3200, '{}'::jsonb, 'pieza', '{"potencia_w": 450}'::jsonb),
  ('SOL-PAN-CANADIAN-440W', 'panel', 'Panel Solar Canadian Solar 440W', 'Canadian Solar', null, 'Panel estándar usado en los paquetes Starter a Elite.', 3100, '{}'::jsonb, 'pieza', '{"potencia_w": 440}'::jsonb),
  ('REF-FILTRO-CAT-001', 'refaccion', 'BELLOWS 7 KW (PAR) GENERAC 0C9592', 'GENERAC', 'C15', 'Filtro de aceite original para motores Caterpillar C15.', 450, '{}'::jsonb, 'pieza', '{"subcategoria": "Filtros"}'::jsonb),
  ('0E6154', 'refaccion', 'BOBINA UTILITY GENERAC 0E6154 200A', 'GENERAC', null, null, 990, '{}'::jsonb, 'pieza', '{"subcategoria": "ATS"}'::jsonb),
  ('0E7079', 'refaccion', 'BUJÍA GENERAC 0E7079', 'GENERAC', 'rs14cy', null, 200, '{}'::jsonb, 'pieza', '{"subcategoria": "BUJIAS"}'::jsonb),
  ('0F3158', 'refaccion', '(0F3158) OIL COOLER G3 GENERAC', 'GENERAC', null, null, null, '{}'::jsonb, 'pieza', '{}'::jsonb),
  ('0C4138', 'refaccion', 'EMPAQUE DE ESCAPE GENERAC 0C4138', 'GENERAC', '0C4138', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "EMPAQUES"}'::jsonb),
  ('0C4647', 'refaccion', 'EMPAQUE DE SOLENOIDE GENERAC 0C4647', 'GENERAC', '0C4647', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "EMPAQUES"}'::jsonb),
  ('0C3150', 'refaccion', 'EMPAQUE TAPA DE BALANCÍN GENERAC 0C3150', 'GENERAC', '0C3150', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "EMPAQUES"}'::jsonb),
  ('0C2979', 'refaccion', 'EMPAQUE TAPA DE VÁLVULAS GENERAC 0C2979', 'GENERAC', '0C2979', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "EMPAQUES"}'::jsonb),
  ('0L3081A', 'refaccion', 'ESPREA ROJA DE ENTRADA A MEZCLADOR 0L3081A', 'GENERAC', '0L3081A', null, null, '{}'::jsonb, 'pieza', '{}'::jsonb),
  ('070185ES-G', 'refaccion', 'FILTRO ACEITE GENERICO (070185ES)', 'GENERAC', '070185ES', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "FILTRO DE ACEITE"}'::jsonb),
  ('0F5419', 'refaccion', 'FILTRO AIRE GENERAC 0F5419', 'GENERAC', '0F5419', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "FILTRO DE AIRE"}'::jsonb),
  ('22676', 'refaccion', 'FUSIBLE 15A GENERAC 022676', 'GENERAC', '22676', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "FUSIBLES"}'::jsonb),
  ('99727', 'refaccion', 'FUSIBLE 5A GENERAC 099727', 'GENERAC', '99727', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "FUSIBLES"}'::jsonb),
  ('0A9611', 'refaccion', 'FUSIBLE 7.5A GENERAC 0A9611', 'GENERAC', '0A9611', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "FUSIBLES"}'::jsonb),
  ('0D7178T', 'refaccion', 'FUSIBLE ATO 7.5A GENERAC 0D7178T', 'GENERAC', '0D7178T', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "FUSIBLES"}'::jsonb),
  ('0663860SRV', 'refaccion', 'PORTA CARBÓN GENERAC 0663860SRV', 'GENERAC', null, null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0K2098', 'refaccion', 'RELAY 12V 25A GENERAC 0C2174', 'GENERAC', '0K2098', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0K2035', 'refaccion', 'RETEN DE ACEITE GENERAC 0E9842', 'GENERAC', '0K2035', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0C3025', 'refaccion', 'SWITCH DE PRESIÓN DE ACEITE 1/4" GENERAC 0C3025', 'GENERAC', '0C3025', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0L2910', 'refaccion', 'MECANISMO TRANSFERENCIA 100 AMP GENERAC 0L2910 (0C2237)', 'GENERAC', '0L2910', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "ATS"}'::jsonb),
  ('0E4494', 'refaccion', 'SWITCH ON-OFF-ON GENERAC 0E4494', 'GENERAC', '0E4494', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION GASOLINA"}'::jsonb),
  ('0H06430SRV', 'refaccion', 'TARJETA PANEL DE CONTROL GENERAC 0H0643 (0H06430SRV)', 'GENERAC', '0H06430SRV', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0D5419', 'refaccion', '(OD5419) FILTRO DE ACEITE GENERAC', 'GENERAC', '0D5419', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "FILTRO DE ACEITE"}'::jsonb),
  ('0E2507', 'refaccion', 'SENSOR DE NIVEL DE REFRIGERANTE GENERAC 0E2507', 'GENERAC', '0E2507', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "SENSORES"}'::jsonb),
  ('0E0502', 'refaccion', 'ENVIADOR DE TEMPERATURA GENERAC 0E0502', 'GENERAC', '0E0502', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "SENSORES"}'::jsonb),
  ('0G0952', 'refaccion', 'BANDA V GENERAC 0G0952', 'GENERAC', '0G0952', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "BANDAS"}'::jsonb),
  ('0G8853', 'refaccion', 'BOBINA DE INICIO GENERAC 0G8853', 'GENERAC', '0G8853', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION LIQUIDCOOLED"}'::jsonb),
  ('0D2244M', 'refaccion', 'ASSY MAGPICKUP (3/8-24 MALE)', 'GENERAC', '0D2244M', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION LIQUIDCOOLED"}'::jsonb),
  ('0H1827', 'refaccion', 'SENSOR NIVEL DE REFRIGERANTE GENERAC 0H1827', 'GENERAC', '0H1827', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION LIQUIDCOOLED"}'::jsonb),
  ('0E42710SRV', 'refaccion', 'MOTOR DE ARRANQUE GENERAC 0E42710SRV', 'GENERAC', '0E42710SRV', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0A8584', 'refaccion', 'SENSOR DE PRESION DE ACEITE GENERAC 0A8584', 'GENERAC', '0A8584', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0E4394', 'refaccion', 'ACTUADOR GENERAC 0E4394 (RG038KW)', 'GENERAC', '0E4394', 'RG038KW', null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION  LIQUIDCOOLED"}'::jsonb),
  ('0G3553', 'refaccion', 'FAN RADIATOR 1.6 GENERAC 0G3553', 'GENERAC', '0G3553', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION LIQUIDCOOLED"}'::jsonb),
  ('0J8415', 'refaccion', '(0J8415) PORTAESCOBILLAS DE DOS CANALES GENERAC', 'GENERAC', '0J8415', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('077220A', 'refaccion', 'BOBINA DE TRANSFERENCIA GENERAC 077220A', 'GENERAC', '077220A', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "ATS"}'::jsonb),
  ('0F3869', 'refaccion', 'SENSOR DE PRESION DE GAS GENERAC 0F3869', 'GENERAC', '0F3869', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION LIQUIDCOOLED"}'::jsonb),
  ('0A45310244', 'refaccion', 'FILTRO DE ACEITE GENERAC 0A45310244', 'GENERAC', '0A45310244', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION LIQUIDCOOLED"}'::jsonb),
  ('0E9368', 'refaccion', 'BUJIA GENERAC 0E9368 (BP6ES)', 'GENERAC', '0E9368', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION GASOLINA"}'::jsonb),
  ('G059402', 'refaccion', '(G059402) FILTRO DE AIRE GENERAC', 'GENERAC', 'G059402', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION LIQUIDCOOLED"}'::jsonb),
  ('0E7080', 'refaccion', 'OIL FILTER 1.6,2.5,3.0,4.2L G3  0E7080', 'GENERAC', '0E7080', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION LIQUIDCOOLED"}'::jsonb),
  ('070185ES', 'refaccion', '(070185ES) FILTRO DE ACEITE GENERAC', 'GENERAC', '070185ES', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0G5894', 'refaccion', 'FILTRO DE AIRE GENERAC 0G5894', 'GENERAC', '0G5894', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0E9371AS', 'refaccion', 'FILTRO DE AIRE GENERAC 0E9371AS', 'GENERAC', '0E9371AS', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0D9723S', 'refaccion', 'FILTRO DE AIRE GENERAC 0D9723S', 'GENERAC', '0D9723S', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0J8371C', 'refaccion', 'ASSY CNTRLR AC HSB 0J8371C GENERAC EVO 1.0', 'GENERAC', '0J8371C', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('10000027421', 'refaccion', 'MEZCLADOR DE MONTAJE 10000027421 GENERAC 14/16KW', 'GENERAC', '10000027421', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('10000004916', 'refaccion', 'ASSY IGN COIL R128.3 X 335 10000004916', 'GENERAC', '10000004916', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('10000004931', 'refaccion', 'ASSY IGN COIL R128.3 X 390 10000004931', 'GENERAC', '10000004931', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0G3224TA', 'refaccion', 'BOBINA DE INICIO GENERAC 0G3224TA', 'GENERAC', '0G3224TA', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('0G3224TB', 'refaccion', 'BOBINA DE INICIO GENERAC 0G3224TB', 'GENERAC', '0G3224TB', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('10000003275', 'refaccion', '(10000003275) CONTROLADOR 2020 AC HSB GENERAC EVO 2.0', 'GENERAC', '10000003275', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('A0000501971', 'refaccion', '(A0000501971) MOTOR DE ARRANQUE ENGRANAJE REDUCIDO 1KW', 'GENERAC', 'A0000501971', null, null, '{}'::jsonb, 'pieza', '{"subcategoria": "GENERACION AIRCOOLED"}'::jsonb),
  ('RENT-GEN-4KVA-GASOLINA', 'renta', 'Generador 4KVA Gasolina Bivoltaje', 'Generac', null, 'Ideal para obra, eventos o respaldo doméstico. Incluye entrega y recolección en Mérida.', 400, '{"24hr": 400, "48hr": 600, "semana": 800}'::jsonb, 'servicio', '{"kva": "4 KVA", "combustible": "Gasolina"}'::jsonb),
  ('PKG-STARTER', 'paquete_solar', 'Starter', null, null, 'Instalación con personal certificado | Inversor GroWatt | Trámite ante CFE | Garantía 25 años paneles', 40000, '{"estandar": 40000, "hibrido": 52000}'::jsonb, 'servicio', '{"paneles": 4, "kw": 1.8, "ahorro_mensual": "$600–$900", "popular": "no"}'::jsonb),
  ('PKG-ESSENTIAL', 'paquete_solar', 'Essential', null, null, 'Instalación con personal certificado | Inversor GroWatt | Trámite ante CFE | Garantía 25 años paneles', 53999, '{"estandar": 53999, "hibrido": 68000}'::jsonb, 'servicio', '{"paneles": 6, "kw": 2.7, "ahorro_mensual": "$900–$1,400", "popular": "no"}'::jsonb),
  ('PKG-COMFORT', 'paquete_solar', 'Comfort', null, null, 'Instalación con personal certificado | Inversor GroWatt | Trámite ante CFE | Garantía 25 años paneles', 64999, '{"estandar": 64999, "hibrido": 80000}'::jsonb, 'servicio', '{"paneles": 8, "kw": 3.6, "ahorro_mensual": "$1,200–$1,800", "popular": "si"}'::jsonb),
  ('PKG-PLUS', 'paquete_solar', 'Plus', null, null, 'Instalación con personal certificado | Inversor GroWatt | Trámite ante CFE | Garantía 25 años paneles', 73999, '{"estandar": 73999, "hibrido": 91000}'::jsonb, 'servicio', '{"paneles": 10, "kw": 4.5, "ahorro_mensual": "$1,500–$2,200", "popular": "no"}'::jsonb),
  ('PKG-PREMIUM', 'paquete_solar', 'Premium', null, null, 'Instalación con personal certificado | Inversor GroWatt | Trámite ante CFE | Garantía 25 años paneles', 84999, '{"estandar": 84999, "hibrido": 104000}'::jsonb, 'servicio', '{"paneles": 12, "kw": 5.4, "ahorro_mensual": "$1,800–$2,700", "popular": "no"}'::jsonb),
  ('PKG-ELITE', 'paquete_solar', 'Elite', null, null, 'Instalación con personal certificado | Inversor GroWatt | Trámite ante CFE | Garantía 25 años paneles', 99000, '{"estandar": 99000, "hibrido": 120000}'::jsonb, 'servicio', '{"paneles": 14, "kw": 6.3, "ahorro_mensual": "$2,100–$3,200", "popular": "no"}'::jsonb)
on conflict (sku) do nothing;

-- Existencias del Excel como ajuste inicial. De aquí en adelante el
-- inventario solo se mueve con movimientos, nunca editando un número.
insert into movimientos_inventario (producto_id, tipo, cantidad, referencia, notas)
select p.id, 'ajuste', v.cant, 'carga-inicial', 'Existencia inicial del Excel'
from (values
  ('GEN-IQ2KW', 5),
  ('GEN-IQ3KW', 5),
  ('GAS-GP3600', 5),
  ('GAS-GP8000E', 5),
  ('GAS-CX8000', 5),
  ('GAS-CX5500', 5),
  ('GAS-PM3800', 5),
  ('AIR-10KW', 5),
  ('AIR-14KW', 5),
  ('AIR-18KW', 5),
  ('AIR-20KW', 5),
  ('AIR-22KW', 5),
  ('AIR-24KW', 5),
  ('AIR-26KW', 5),
  ('LIQ-32', 5),
  ('LIQ-34', 5),
  ('BAT-PYLONTECH-US2000C', 5),
  ('BAT-PYLONTECH-US3000C', 5),
  ('BAT-BYD-BATTERY-BOX-5KWH', 5),
  ('BAT-GROWATT-ARK-2-56H', 5),
  ('BAT-SOLIS-RHI-BAT-6KWH', 5),
  ('BAT-TROJAN-T-105-AGM', 5),
  ('BAT-PYLONTECH-FORCE-H2', 5),
  ('BAT-BYD-BATTERY-BOX-PREMIUM-15KWH', 5),
  ('BAT-GROWATT-ARK-HV-20KWH', 5),
  ('BAT-SOFAR-BTS-E20-DS5', 5),
  ('BAT-VISION-HF12-200A-AGM', 5),
  ('BAT-DYNESS-POWERRACK-B4850', 5),
  ('BAT-CATL-ENERC-100KWH', 5),
  ('BAT-BYD-MC-CUBE-T', 5),
  ('BAT-PYLONTECH-POWERCUBE-X-RC15', 5),
  ('BAT-CATL-ENERONE-50KWH', 5),
  ('BAT-DYNESS-INDUSTRIAL-75KWH', 5),
  ('BAT-GROWATT-SPF-3000TL-HV', 5),
  ('SOL-PAN-JINKO-450W', 25),
  ('SOL-PAN-CANADIAN-440W', 40),
  ('REF-FILTRO-CAT-001', 8),
  ('0E6154', 10),
  ('0E7079', 10),
  ('RENT-GEN-4KVA-GASOLINA', 3)
) as v(sku, cant) join productos p on p.sku = v.sku;

-- Productos sin precio en el Excel (quedaron en null, hay que capturarlos):
-- 0F3158, 0C4138, 0C4647, 0C3150, 0C2979, 0L3081A, 070185ES-G, 0F5419, 22676, 99727, 0A9611, 0D7178T, 0663860SRV, 0K2098, 0K2035, 0C3025, 0L2910, 0E4494, 0H06430SRV, 0D5419, 0E2507, 0E0502, 0G0952, 0G8853, 0D2244M, 0H1827, 0E42710SRV, 0A8584, 0E4394, 0G3553, 0J8415, 077220A, 0F3869, 0A45310244, 0E9368, G059402, 0E7080, 070185ES, 0G5894, 0E9371AS, 0D9723S, 0J8371C, 10000027421, 10000004916, 10000004931, 0G3224TA, 0G3224TB, 10000003275, A0000501971